language: java

#dist: trusty
jdk:
  - openjdk8
#scala:
#  - 2.11.8

git:
  quiet: true
cache:
  directories:
    - $HOME/.m2

# keep 30, need change according to ci logs.
script:
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xms500m -Xmx1g -XX:MaxPermSize=256m -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  - mvn -B clean test -Dlogging.level.org.springframework=WARN
